apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web
  namespace: node-challenge
  labels:
    app: node-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-web
  template:
    metadata:
      labels:
        app: node-web
    spec:
      containers:
        - name: node-web
          image: docker.io/teaf/node-app:v1.0.0
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: BANNER
              valueFrom:
                configMapKeyRef:
                  name: node-web-config
                  key: BANNER
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
