apiVersion: v1
kind: Service
metadata:
  name: node-public
  namespace: node-challenge
  labels:
    app: node-web
spec:
  type: LoadBalancer
  selector:
    app: node-web
  ports:
    - port: 80
      targetPort: 3000
