apiVersion: v1
kind: Service
metadata:
  name: node-clusterip
  namespace: node-challenge
  labels:
    app: web
spec:
  type: ClusterIP
  selector:
    app: node-web
  ports:
    - port: 3000
      targetPort: 3000
